export const SystemEvents = {
    SESSION_START: 'SESSION_START',
    SESSION_END: 'SESSION_END',

    TASK_START: 'TASK_START',
    TASK_ATTEMPT: 'TASK_ATTEMPT',
    TASK_RETRY: 'TASK_RETRY',
    TASK_SUCCESS: 'TASK_SUCCESS',
    TASK_FAILURE: 'TASK_FAILURE',
    TASK_SKIP: 'TASK_SKIP',
};
